name: Deploy Nucleus

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Deploy to Linode VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory
            cd /var/www/nucleus || {
              git clone https://github.com/${{ github.repository }}.git /var/www/nucleus
              cd /var/www/nucleus
            }
            
            # Pull latest changes
            git pull origin main
            
            # Copy environment file (make sure it's configured on the server)
            # cp /var/www/nucleus/.env.production .env
            
            # Stop existing containers
            docker compose down
            
            # Build and start new containers
            docker compose up -d --build
            
            # Clean up old images
            docker image prune -af
            
            # Show running containers
            docker compose ps

      - name: Health check
        run: |
          echo "Waiting for services to start..."
          sleep 30
          # Add health check endpoint verification here
          # curl -f http://${{ secrets.LINODE_IP }}/health || exit 1

      - name: Notify deployment status
        if: always()
        run: |
          echo "Deployment finished with status: ${{ job.status }}"

